language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
    - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && npm test || npm run build'

# safelist
branches:
  only:
  - master
  
   