export const lightTheme = {
  body: '#E8EAED',
  text: '#4E5B6E',
  btnBackground: '#000',
  btnBorderColor: '#E5E9F2',
  btnFontColor: '#FFE300',
  outBtnBackground: '#EFF2F7',
  outBtnBorderColor: '#E5E9F2',
  cardBorderColor: '#4BD5EE',
  cardBackground: '#FFF',
  inputBackground: '#EFF2F7',
  inputBorderColor: '#E5E9F2',
  inputFontColor: '#3C4858',
  barBackground: '#000',
  barBorderColor: '#333',
  barFontColor: '#4BD5EE',
  headingFontColor: '#4BD5EE',
  titleFontColor: '#4E5B6E',
  radarFontColor: '#FFE300',
  radarBackground: '#000',
  radarGrid: '#3C4858',
  credentials: '#FFE300'
}

export const darkTheme = {
  body: '#000',
  text: '#abb1ba',
  btnBackground: '#4BD5EE',
  btnBorderColor: 'none',
  btnFontColor: '#FFE300',
  outBtnBackground: '#333',
  outBtnBorderColor: '#3C4858',
  cardBorderColor: '#FFE300',
  cardBackground: '#333',
  inputBackground: '#FFF',
  inputBorderColor: '#3C4858',
  inputFontColor: '#273444',
  barBackground: '#333',
  barBorderColor: '#3C4858',
  barFontColor: '#4BD5EE',
  headingFontColor: '#FFE300',
  titleFontColor: '#4BD5EE',
  radarFontColor: '#4BD5EE',
  radarBackground: '#000',
  radarGrid: '#333',
  credentials: '#4BD5EE'
}